Repository DependencyTrack/frontend, pull requests merged in 2022-09, with the labels that each got.

#239 Calculate CVSS scores dynamically when only the vector is known
  src/views/portfolio/vulnerabilities/VulnerabilityDetailsModal.vue
Labels: defect

#240 Fix minor API keys display issues
  src/views/administration/accessmanagement/Teams.vue
Labels: defect

#242 Issue 1903 : OSV - user-enabled list of ecosystem
  src/i18n/locales/en.json
  src/shared/api.json
  src/views/administration/vuln-sources/EcosystemModal.vue
  src/views/administration/vuln-sources/VulnSourceOSVAdvisories.vue
Labels: enhancement

#246 Bump `merge` to 2.1.1
  package-lock.json
  package.json
Labels: dependencies, security, javascript

#254 Add missing translation calls
  src/i18n/locales/en.json
  src/views/administration/configuration/BomFormats.vue
  src/views/dashboard/ChartEpssVsCvss.vue
  src/views/dashboard/ChartPolicyViolationBreakdown.vue
  src/views/portfolio/projects/ProjectFindings.vue
  src/views/portfolio/projects/ProjectUploadBomModal.vue
  src/views/portfolio/projects/ProjectUploadVexModal.vue
Labels: localization

#256 Issue 1964: OSV base url customised
  src/i18n/locales/en.json
  src/views/administration/vuln-sources/VulnSourceOSVAdvisories.vue
Labels: enhancement

#259 Add CVSS, EPSS to Component Vulnerabilities
  src/views/portfolio/projects/ComponentVulnerabilities.vue
Labels: enhancement
