Repository DependencyTrack/frontend, pull requests merged in 2022-10, with the labels that each got.

#277 Re-enable NEW_VULNERABLE_DEPENDENCY notification
  src/views/administration/notifications/Alerts.vue
Labels: enhancement

#274 Include a projects children in an alert rules limitations
  src/i18n/locales/en.json
  src/views/administration/notifications/Alerts.vue
Labels: enhancement

#293 Add release documentation
  .github/images/release-branch.png
  .github/images/release-master.png
  RELEASING.md
Labels: documentation

#297 Enable release creation from non-master branches
  .github/workflows/ci-release.yaml
Labels: enhancement, ci

#296 Enable release creation from non-master branches
  .github/images/release-branch.png
  .github/images/release-releasebranch.png
  .github/workflows/ci-release.yaml
  RELEASING.md
Labels: enhancement, ci

#303 Specify the target branch when creating a release via GitHub CLI
  .github/workflows/ci-release.yaml
Labels: ci

#304 Specify the target branch when creating a release via GitHub CLI
  .github/workflows/ci-release.yaml
Labels: ci
