Repository DependencyTrack/frontend, pull requests merged in 2023-04, with the labels that each got.

#461 fix Duplicate Key of 'last_bom_import'
  src/i18n/locales/en.json
Labels: defect

#380 Added new project notification to frontend alert template
  src/views/administration/notifications/Alerts.vue
Labels: enhancement

#467 Allow for vulnerability alias synchronization to be disabled for each source that supports it
  src/i18n/locales/en.json
  src/views/administration/analyzers/OssIndexAnalyzer.vue
  src/views/administration/analyzers/SnykAnalyzer.vue
  src/views/administration/vuln-sources/VulnSourceGitHubAdvisories.vue
  src/views/administration/vuln-sources/VulnSourceOSVAdvisories.vue
Labels: enhancement

#315 aliases: improve alias column, show aliases optionally in all vulnerability lists
  src/views/portfolio/projects/ComponentVulnerabilities.vue
  src/views/portfolio/projects/ProjectFindings.vue
  src/views/portfolio/vulnerabilities/VulnerabilityList.vue
Labels: enhancement

#480 Bump version in issue template
  .github/ISSUE_TEMPLATE/defect-report.yml
Labels: documentation

#482 Fix aliases hyperlink on component vulnerabilities page
  src/views/portfolio/projects/ComponentVulnerabilities.vue
Labels: defect
