Repository DependencyTrack/frontend, pull requests merged in 2024-01, with the labels that each got.

#689 Refactor finding detail and fix finding search routes
  src/router/index.js
  src/views/portfolio/projects/FindingAudit.vue
  src/views/portfolio/projects/ProjectFindings.vue
  src/views/portfolio/vulnerabilities/AffectedProjects.vue
  vue.config.js
Labels: defect

#699 docs: fix build status badge
  README.md
Labels: documentation

#704 fix: correctly calculate audited violations and audited findings percentages
  src/views/Dashboard.vue
Labels: defect

#707 feat(violations): add current fail, warn, info metrics to footer
  src/views/Dashboard.vue
Labels: enhancement

#708 fix(common): calculate percentage to tenth decimal place
  src/shared/common.js
Labels: enhancement

#712 refactor(dashboard): use consistent color for suppressed
  src/views/Dashboard.vue
Labels: enhancement

#710 refactor(dashboard): remove unused policy violations widget
  src/views/dashboard/WidgetPolicyViolations.vue
Labels: technical debt

#713 refactor(dashboard): set progress colors via scss
  src/assets/scss/_custom.scss
  src/views/Dashboard.vue
Labels: enhancement

#709 feat(dashboard): display additional portfolio statistics
  src/views/Dashboard.vue
Labels: enhancement

#714 feat(dashboard): add vuln / non-vuln footer to projects and components cards
  src/assets/scss/_variables.scss
  src/i18n/locales/en.json
  src/views/Dashboard.vue
  src/views/dashboard/ChartComponentVulnerabilities.vue
  src/views/dashboard/ChartProjectVulnerabilities.vue
Labels: enhancement

#715 feat(dashboard): auditing progress for findings and policy violations
  src/i18n/locales/en.json
  src/views/Dashboard.vue
  src/views/dashboard/ChartAuditingFindingsProgress.vue
  src/views/dashboard/ChartAuditingViolationsProgress.vue
  src/views/portfolio/projects/ComponentDashboard.vue
  src/views/portfolio/projects/ProjectDashboard.vue
  src/views/portfolio/projects/ServiceDashboard.vue
Labels: enhancement
