Repository DependencyTrack/frontend, pull requests merged in 2024-11, with the labels that each got.

#1078 docker: fix ipv6 listening
  docker/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
Labels: defect

#1082 Fix tags with special characters breaking the tags table
  src/views/portfolio/tags/TagList.vue
Labels: defect, backport/4.12.2

#1091 Fix no error being displayed when submitting an invalid welcome message
  src/views/administration/configuration/WelcomeMessage.vue
Labels: defect, backport/4.12.2

#1095 Show component properties to users with VIEW_PORTFOLIO permission
  src/views/portfolio/projects/ComponentDetailsModal.vue
  src/views/portfolio/projects/ComponentPropertiesModal.vue
Labels: defect, backport/4.12.2

#1060 Added buttons to add/delete/edit the affected Components
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/portfolio/vulnerabilities/AddAffectedComponentModal.vue
  src/views/portfolio/vulnerabilities/VulnerabilityDetailsModal.vue
Labels: enhancement

#1098 Fix missing URI encoding for vulnerability IDs
  src/views/globalAudit/VulnerabilityAuditByOccurrence.vue
  src/views/globalAudit/VulnerabilityAuditGroupedByVulnerability.vue
  src/views/portfolio/projects/ProjectFindings.vue
  src/views/portfolio/vulnerabilities/AffectedProjects.vue
  src/views/portfolio/vulnerabilities/Vulnerability.vue
  src/views/portfolio/vulnerabilities/VulnerabilityCreateVulnerabilityModal.vue
  src/views/portfolio/vulnerabilities/VulnerabilityList.vue
Labels: defect, backport/4.12.2

#1099 Backport: Fix no error being displayed when submitting an invalid welcome message
  src/views/administration/configuration/WelcomeMessage.vue
Labels: defect

#1100 Backport: Fix tags with special characters breaking the tags table
  src/views/portfolio/tags/TagList.vue
Labels: defect
