Repository DependencyTrack/frontend, pull requests merged in 2024-10, with the labels that each got.

#1028 Fix creation of multiple projects without reloading page
  src/views/portfolio/projects/ProjectCreateProjectModal.vue
Labels: defect, backport/4.12.1

#1034 fix: Add Oidc user to team view
  src/views/administration/accessmanagement/Teams.vue
Labels: defect, backport/4.12.1

#1032 State should now also in not Snapshot version saved
  src/containers/DefaultContainer.vue
Labels: defect, backport/4.12.1

#1043 Backport: Add `.gitattributes` to fix prettier behavior on Windows
  .gitattributes
Labels: dx

#1044 Backport: Fix state of sidebar not being saved for non-`SNAPSHOT` versions
  src/containers/DefaultContainer.vue
Labels: defect

#1045 Backport: Fix OIDC users not being displayed in Team view
  src/views/administration/accessmanagement/Teams.vue
Labels: defect

#1046 Backport: Fix creation of multiple projects without reloading page
  src/views/portfolio/projects/ProjectCreateProjectModal.vue
Labels: defect

#1050 Fix caching issues upon upgrade
  docker/etc/nginx/templates/default.conf.template
Labels: defect

#1049 Backport: Always display project nodes in dependency graph using name and version
  src/views/portfolio/projects/ProjectDependencyGraph.vue
Labels: defect

#1051 Backport: Fix caching issues upon upgrade
  docker/etc/nginx/templates/default.conf.template
Labels: defect

#1039 Fix: "Add Version" Create Button Should Be Inactive Until Version Provided
  src/views/portfolio/projects/ProjectAddVersionModal.vue
Labels: defect, hacktoberfest, hacktoberfest-accepted

#1052 Backport: Fix: "Add Version" Create Button Should Be Inactive Until Version Provided
  src/views/portfolio/projects/ProjectAddVersionModal.vue
Labels: defect

#1056 Fix missing URI encoding of tag names
  src/views/portfolio/tags/TagList.vue
  src/views/portfolio/tags/TaggedNotificationRuleListModal.vue
  src/views/portfolio/tags/TaggedPoliciesListModal.vue
  src/views/portfolio/tags/TaggedProjectListModal.vue
Labels: defect, backport/4.12.1

#1057 Backport: Fix missing URI encoding of tag names
  src/views/portfolio/tags/TagList.vue
  src/views/portfolio/tags/TaggedNotificationRuleListModal.vue
  src/views/portfolio/tags/TaggedPoliciesListModal.vue
  src/views/portfolio/tags/TaggedProjectListModal.vue
Labels: defect

#1063 docker: fix ipv6 listening
  docker/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
Labels: defect, backport/4.12.1

#1066 fix: breadcrumbs navigation broken for non-english language
  src/containers/DefaultContainer.vue
  src/router/index.js
Labels: defect, hacktoberfest-accepted, backport/4.12.1

#1068 Backport: Fix breadcrumbs navigation being broken for non-english languages
  src/containers/DefaultContainer.vue
  src/router/index.js
Labels: defect

#1069 Backport: Fix NGINX ipv6 listening
  docker/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
Labels: defect

#1074 Bump nginxinc/nginx-unprivileged to 1.27.2-alpine
  docker/Dockerfile.alpine
Labels: dependencies
