Repository DependencyTrack/frontend, pull requests merged in 2024-08, with the labels that each got.

#848 feat(components): quick search for projects also using component
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/portfolio/projects/Component.vue
Labels: enhancement

#963 Bump `nginxinc/nginx-unprivileged` to `bb3225a`
  docker/Dockerfile.alpine
Labels: dependencies, docker

#964 Backport: French translation update
  src/i18n/locales/fr.json
Labels: enhancement, i18n

#949 Add ability to test notification publishers
  src/views/administration/notifications/Alerts.vue
Labels: enhancement

#971 fix: Fix some translations in spanish
  src/i18n/locales/es.json
Labels: enhancement, i18n

#810 feat: dynamic policy violation badges based on show suppressed flag
  src/views/portfolio/projects/Project.vue
  src/views/portfolio/projects/ProjectPolicyViolations.vue
Labels: enhancement

#980 Add "limit to tags" option for alerts
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/administration/notifications/Alerts.vue
  src/views/portfolio/tags/TagList.vue
  src/views/portfolio/tags/TaggedNotificationRuleListModal.vue
Labels: enhancement
