Repository DependencyTrack/frontend, pull requests merged in 2024-05, with the labels that each got.

#837 Add i18n documentation
  .github/images/i18n_i18n-ally-progress.png
  .github/images/i18n_i18n-ally-translate.png
  .github/images/i18n_language-picker.png
  README.md
Labels: documentation, i18n

#839 Force page reload after locale change
  src/views/components/LocalePicker.vue
Labels: enhancement

#840 Fix some issues in German translation
  src/i18n/locales/de.json
Labels: i18n

#842 Run builds and CI on `feature-*` branches
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-build.yaml
  .github/workflows/ci-publish.yaml
  .github/workflows/codeql-analysis.yaml
  .github/workflows/i18n.yaml
  .github/workflows/lint.yaml
Labels: dx

#845 Add missing repo views for Hackage and Nixpkgs
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/router/index.js
  src/views/administration/AdminMenu.vue
  src/views/administration/Administration.vue
  src/views/administration/repositories/Hackage.vue
  src/views/administration/repositories/Nixpkgs.vue
Labels: defect

#861 Restrict Height Of Project Versions Dropdown
  src/views/portfolio/projects/Project.vue
Labels: defect

#862 Distinguish Between Active And Inactive Project Versions
  src/views/portfolio/projects/Project.vue
Labels: enhancement

#868 Improve Japanese translation
  src/i18n/locales/ja.json
Labels: enhancement, i18n

#869 Backport: Improve Japanese translation
  src/i18n/locales/ja.json
Labels: enhancement, i18n

#870 Add database name and version to About dialog
  src/views/components/AboutModal.vue
Labels: enhancement

#872 Show Badge For Inactive Projects
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/portfolio/projects/Project.vue
Labels: enhancement

#871 Bind i18n Object To SeverityProgressBar Props
  src/views/portfolio/components/ComponentSearch.vue
  src/views/portfolio/projects/ProjectComponents.vue
  src/views/portfolio/projects/ProjectServices.vue
Labels: defect

#873 Backport: Bind i18n Object To SeverityProgressBar Props
  src/views/portfolio/components/ComponentSearch.vue
  src/views/portfolio/projects/ProjectComponents.vue
  src/views/portfolio/projects/ProjectServices.vue
Labels: defect

#877 Updates english translation
  src/i18n/locales/en.json
Labels: i18n

#878 Updates french translation
  src/i18n/locales/fr.json
Labels: i18n
