Repository DependencyTrack/frontend, pull requests merged in 2024-06, with the labels that each got.

#882 Backport: Restrict Height Of Project Versions Dropdown
  src/views/portfolio/projects/Project.vue
Labels: defect

#883 Backport: Update english translation
  src/i18n/locales/en.json
Labels: enhancement, i18n

#884 Backport: Update french translation
  src/i18n/locales/fr.json
Labels: enhancement, i18n

#885 Backport: build(deps): bump nginxinc/nginx-unprivileged in /docker
  docker/Dockerfile.alpine
Labels: dependencies, docker

#886 Add BOM_VALIDATION_FAILED To Notification Group
  src/views/administration/notifications/Alerts.vue
Labels: enhancement

#892 i18n: improve chinese localization quality
  src/i18n/locales/zh.json
Labels: enhancement, i18n

#898 i18n: Improve German Translation #890
  src/i18n/locales/de.json
Labels: enhancement, i18n

#902 Configure prettier to sort JSON files
  .prettierrc.json
  package-lock.json
  package.json
  public/static/config.json
  src/shared/api.json
  src/shared/oidc.json
Labels: enhancement, dx

#907 Sort Components Vulnerabilities by Severity or CWE
  src/views/portfolio/projects/ComponentVulnerabilities.vue
Labels: enhancement

#917 Backport: Improve German translation
  src/i18n/locales/de.json
Labels: enhancement, i18n

#918 Backport: Improve Chinese Localization Quality
  src/i18n/locales/zh.json
Labels: enhancement, i18n

#922 Add tag management view
  src/containers/DefaultContainer.vue
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/router/index.js
  src/views/portfolio/tags/TagList.vue
  src/views/portfolio/tags/TaggedPoliciesListModal.vue
  src/views/portfolio/tags/TaggedProjectListModal.vue
Labels: enhancement

#923 Make tagged project names clickable
  src/views/administration/accessmanagement/SelectProjectModal.vue
  src/views/portfolio/tags/TaggedProjectListModal.vue
Labels: enhancement

#927 Raise baseline Node version to 20
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-build.yaml
  .github/workflows/ci-publish.yaml
  .github/workflows/ci-release.yaml
  .github/workflows/i18n.yaml
  .github/workflows/lint.yaml
  .nvmrc
  package.json
Labels: technical debt

#928 Add ability to delete tags and untag projects
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/mixins/permissionsMixin.js
  src/shared/permissions.js
  src/views/portfolio/tags/TagList.vue
  src/views/portfolio/tags/TaggedProjectListModal.vue
Labels: enhancement
