Repository DependencyTrack/frontend, pull requests merged in 2024-04, with the labels that each got.

#798 chore(deps): pin and update to latest minor releases
  package-lock.json
  package.json
Labels: dependencies, javascript

#797 fix: v-for explicit key
  src/views/administration/AdminMenu.vue
Labels: defect

#796 refactor: perform saas slash-div migration
  src/assets/scss/vendors/bootstrap/_variables.scss
Labels: enhancement

#793 feat(license): use concise endpoint for license list view
  src/views/portfolio/licenses/LicenseList.vue
Labels: enhancement

#792 feat(license): add deprecated column
  src/views/portfolio/licenses/LicenseList.vue
Labels: enhancement

#803 Add Comment Column To External References
  src/views/portfolio/projects/ComponentDetailsModal.vue
  src/views/portfolio/projects/ProjectDetailsModal.vue
  src/views/portfolio/projects/ServiceDetailsModal.vue
Labels: enhancement

#805 add support from localization based on browser and languages
  .github/workflows/i18n.yaml
  .vscode/extensions.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/i18n/index.js
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/zh.json
  src/views/portfolio/projects/ComponentDetailsModal.vue
  src/views/portfolio/projects/ProjectAddComponentModal.vue
Labels: enhancement

#812 Require `VIEW_PORTFOLIO` permission for BOM download
  src/views/portfolio/projects/ProjectComponents.vue
Labels: defect

#811 Add support for component properties
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/zh.json
  src/views/portfolio/projects/Component.vue
  src/views/portfolio/projects/ComponentCreatePropertyModal.vue
  src/views/portfolio/projects/ComponentDetailsModal.vue
  src/views/portfolio/projects/ComponentPropertiesModal.vue
Labels: enhancement

#816 Enhanced ProgressBar Contrast Ration
  src/views/components/PolicyViolationProgressBar.vue
  src/views/components/SeverityProgressBar.vue
Labels: enhancement

#821 Update Trivy option wording and fix vulnerability source label styling
  src/assets/scss/_custom.scss
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/zh.json
  src/shared/common.js
Labels: enhancement

#824 Add locale picker to header
  package.json
  src/containers/DefaultHeaderProfileDropdown.vue
  src/i18n/index.js
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/zh.json
  src/views/components/LocalePicker.vue
  vue-i18n-extract.config.js
Labels: enhancement

#828 fix missing translation
  src/views/portfolio/projects/ProjectPolicyViolations.vue
Labels: i18n

#795 feat(component-search): add license column
  src/views/portfolio/components/ComponentSearch.vue
Labels: enhancement

#832 Display EPSS Score And Percentile In Vulnerability Page
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/zh.json
  src/views/portfolio/vulnerabilities/Vulnerability.vue
Labels: enhancement

#835 Add Ukrainian 🇺🇦 i18n
  src/i18n/locales/uk-UA.json
Labels: i18n
