Repository DependencyTrack/frontend, pull requests merged in 2024-02, with the labels that each got.

#721 refactor(project details): improve UX for active/inactive toggle.
  src/i18n/locales/en.json
  src/views/portfolio/projects/ProjectDetailsModal.vue
Labels: enhancement

#719 refactor: handle percentage calc edge cases
  src/shared/common.js
Labels: defect

#717 feat(dashboard): policy violations by state and classification cards
  src/views/Dashboard.vue
  src/views/dashboard/ChartPolicyViolationsClassification.vue
  src/views/dashboard/ChartPolicyViolationsState.vue
  src/views/portfolio/projects/ComponentDashboard.vue
  src/views/portfolio/projects/ProjectDashboard.vue
  src/views/portfolio/projects/ServiceDashboard.vue
Labels: enhancement

#718 refactor(dashboard): show portfolio vulnerabilities severity in footer
  src/views/Dashboard.vue
Labels: enhancement

#723 feat(vulnerabilities): support active/inactive affected projects
  src/views/portfolio/vulnerabilities/AffectedProjects.vue
  src/views/portfolio/vulnerabilities/VulnerabilityList.vue
Labels: enhancement

#725 Fix "Outdated Only" button being disabled when dependency graph is not available
  src/views/portfolio/projects/ProjectComponents.vue
Labels: defect

#726 Fix redundant requests to `/api/v1/component` when loading project page
  src/views/portfolio/projects/ProjectComponents.vue
Labels: defect

#727 Fix table column visibility preferences triggering redundant requests
  src/shared/utils.js
Labels: defect

#728 feat(notifications): show publisher name on expanded row
  src/views/administration/notifications/Alerts.vue
Labels: enhancement

#720 New Subject Prefix Input Box
  src/i18n/locales/en.json
  src/views/administration/configuration/Email.vue
Labels: enhancement

#656 Trivy support
  src/assets/img/trivy-logo.svg
  src/i18n/locales/en.json
  src/router/index.js
  src/shared/common.js
  src/views/administration/AdminMenu.vue
  src/views/administration/Administration.vue
  src/views/administration/analyzers/TrivyAnalyzer.vue
  src/views/portfolio/vulnerabilities/Vulnerability.vue
Labels: enhancement

#738 feat(project): add tooltip to vuln progress bar
  src/views/components/SeverityProgressBar.vue
  src/views/portfolio/projects/ProjectList.vue
Labels: enhancement

#736 feat(project): finding badges including and excluding aliases
  src/assets/scss/_custom.scss
  src/i18n/locales/en.json
  src/views/portfolio/projects/Project.vue
Labels: enhancement

#735 build: add @vue/runtime-dom as devDependency
  package-lock.json
  package.json
Labels: dependencies, javascript

#733 feat: improve tooltip clarity for project vulnerabilities
  src/i18n/locales/en.json
  src/views/portfolio/projects/Project.vue
Labels: enhancement

#744 feat(project): policy violation badges
  src/assets/scss/_custom.scss
  src/i18n/locales/en.json
  src/views/portfolio/projects/Project.vue
Labels: enhancement

#411 Global Audit View: Vulnerabilities
  src/containers/DefaultContainer.vue
  src/i18n/locales/en.json
  src/router/index.js
  src/shared/utils.js
  src/views/globalAudit/VulnerabilityAudit.vue
  src/views/globalAudit/VulnerabilityAuditByOccurrence.vue
  src/views/globalAudit/VulnerabilityAuditGroupedByVulnerability.vue
Labels: enhancement

#748 Do not append `@<version>` when rendering CPEs in Affected Components view
  src/views/portfolio/vulnerabilities/VulnerabilityDetailsModal.vue
Labels: defect

#750 chore: bump cyclonedx-npm package for npm10 support
  package-lock.json
  package.json
Labels: technical debt

#751 chore: update engine ranges
  package-lock.json
  package.json
Labels: technical debt

#755 Add auto-generated changelog to GitHub releases
  .github/release.yml
  .github/workflows/ci-publish.yaml
  .github/workflows/ci-release.yaml
Labels: enhancement
