Repository DependencyTrack/frontend, pull requests merged in 2024-12, with the labels that each got.

#1108 Bump nginxinc/nginx-unprivileged to 1.27.3-alpine
  docker/Dockerfile.alpine
Labels: dependencies

#1109 Backport: Improve russian translation
  src/i18n/locales/ru.json
Labels: enhancement, i18n

#1110 Backport: Prefill *Team* input in *Create Project* dialog based on user's team membership
  src/views/portfolio/projects/ProjectCreateProjectModal.vue
Labels: defect

#658 Introduce "collection" projects for better usage of hierarchical view
  src/assets/scss/_custom.scss
  src/assets/scss/_variables.scss
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/mixins/availableClassifiersMixin.js
  src/mixins/availableCollectionLogicsMixin.js
  src/plugins/table.js
  src/router/index.js
  src/shared/common.js
  src/views/dashboard/ChartAuditingFindingsProgress.vue
  src/views/dashboard/ChartAuditingViolationsProgress.vue
  src/views/dashboard/ChartComponentVulnerabilities.vue
  src/views/dashboard/ChartPolicyViolationsState.vue
  src/views/dashboard/ChartPortfolioVulnerabilities.vue
  src/views/portfolio/projects/ComponentDetailsModal.vue
  src/views/portfolio/projects/Project.vue
  src/views/portfolio/projects/ProjectAddComponentModal.vue
  src/views/portfolio/projects/ProjectCollectionProjects.vue
  src/views/portfolio/projects/ProjectCreateProjectModal.vue
  src/views/portfolio/projects/ProjectDetailsModal.vue
  src/views/portfolio/projects/ProjectList.vue
  src/views/portfolio/projects/ProjectListView.vue
Labels: enhancement
