Repository DependencyTrack/frontend, pull requests merged in 2024-07, with the labels that each got.

#801 Feature: add support for serving from custom path
  .dockerignore
  docker/Dockerfile.alpine
  docker/docker-compose.yml
  docker/etc/nginx/templates/default.conf.template
  public/index.html
  public/static/oidc-callback.html
  src/views/pages/Login.vue
  vue.config.js
Labels: enhancement

#930 add EPSS score to policies
  src/views/policy/PolicyCondition.vue
Labels: enhancement

#936 Add autocomplete support for tag inputs
  src/views/portfolio/projects/ProjectCreateProjectModal.vue
  src/views/portfolio/projects/ProjectDetailsModal.vue
Labels: enhancement

#937 Fix usage of deprecated policy tagging endpoints, and add ability to untag policies from *Tags* view
  src/views/policy/PolicyList.vue
  src/views/portfolio/tags/TaggedPoliciesListModal.vue
Labels: enhancement

#941 Backport: Bump `nginxinc/nginx-unprivileged` to 1.27.0
  docker/Dockerfile.alpine
Labels: dependencies, docker

#946 Remove BOM processing V2 toggle
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/administration/AdminMenu.vue
  src/views/administration/configuration/Experimental.vue
Labels: defect

#950 Bump `bootstrap-table` to 1.22.6
  package-lock.json
  package.json
Labels: dependencies, javascript

#957 French translation update
  src/i18n/locales/fr.json
Labels: enhancement, i18n
