Repository DependencyTrack/frontend, pull requests merged in 2025-01, with the labels that each got.

#1129 Remove deprecation notice of toggle for unauthenticated access to SVG badges
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
Labels: documentation

#509 Fix affected projects tab not being updated when switching between vulnerability aliases
  src/views/portfolio/vulnerabilities/AffectedProjects.vue
Labels: defect

#1131 Fix typo in English translation
  src/i18n/locales/en.json
Labels: i18n

#1135 Port: Fix affected projects tab not being updated when switching between vulnerability aliases
  src/views/portfolio/vulnerabilities/AffectedProjects.vue
Labels: defect

#1144 Backport: Bump dompurify from 2.4.9 to 2.5.8
  package-lock.json
  package.json
Labels: defect

#1149 Bump `nginx-unprivileged` base image to latest digest
  docker/Dockerfile.alpine
Labels: dependencies
