Repository DependencyTrack/frontend, pull requests merged in 2025-02, with the labels that each got.

#1152 Add timestamp formatting to chart tooltips
  src/views/dashboard/ChartAuditingFindingsProgress.vue
  src/views/dashboard/ChartAuditingViolationsProgress.vue
  src/views/dashboard/ChartComponentVulnerabilities.vue
  src/views/dashboard/ChartPolicyViolationsClassification.vue
  src/views/dashboard/ChartPolicyViolationsState.vue
  src/views/dashboard/ChartPortfolioVulnerabilities.vue
  src/views/dashboard/ChartProjectVulnerabilities.vue
  src/views/dashboard/WidgetInheritedRiskScore.vue
  src/views/dashboard/WidgetPortfolioVulnerabilities.vue
  src/views/dashboard/WidgetProjectsAtRisk.vue
  src/views/dashboard/WidgetVulnerableComponents.vue
Labels: enhancement

#1157 Handle new API key format and generation process
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/administration/accessmanagement/ApiKeyListGroupItem.vue
  src/views/administration/accessmanagement/EditApiKeyCommentModal.vue
  src/views/administration/accessmanagement/Teams.vue
Labels: enhancement

#1168 Change API key field `clearTextKey` to `key`
  src/views/administration/accessmanagement/ApiKeyListGroupItem.vue
  src/views/administration/accessmanagement/Teams.vue
Labels: enhancement

#1169 Fix column visibility preference not considered for project list
  src/views/portfolio/projects/ProjectList.vue
Labels: defect

#1171 Fix policy violation tab indicators being populated incorrectly
  src/views/portfolio/projects/Project.vue
Labels: defect, backport/4.12.6

#1172 Backport: Fix policy violation tab indicators being populated incorrectly
  src/views/portfolio/projects/Project.vue
Labels: defect

#1173 Bump nginxinc/nginx-unprivileged from 1.27.3-alpine to 1.27.4-alpine
  docker/Dockerfile.alpine
Labels: dependencies

#1174 Fix wrong policy violation tab indicator visibility conditions
  src/views/portfolio/projects/Project.vue
Labels: defect, backport/4.12.6

#1175 Backport: Fix wrong policy violation tab indicator visibility conditions
  src/views/portfolio/projects/Project.vue
Labels: defect

#1164 Add telemetry admin view
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/router/index.js
  src/views/administration/AdminMenu.vue
  src/views/administration/Administration.vue
  src/views/administration/configuration/Telemetry.vue
Labels: enhancement
