Repository DependencyTrack/frontend, pull requests merged in 2025-04, with the labels that each got.

#1213 Fix tag autocomplete dropdown library style overriding issue
  src/assets/scss/vendors/vue-tags-input/_vue-tags-input.scss
Labels: defect

#1209 Add trivy scanner option UI
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/administration/analyzers/TrivyAnalyzer.vue
Labels: enhancement

#1198 Add autocomplete to project collection logic tag dropdown
  src/views/portfolio/projects/ProjectCreateProjectModal.vue
  src/views/portfolio/projects/ProjectDetailsModal.vue
Labels: enhancement

#1210 Integrate scheduled alerts into existing alerts views
  src/App.vue
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/administration/notifications/Alerts.vue
  src/views/administration/notifications/CreateAlertModal.vue
Labels: enhancement

#1217 Fix "show in dependency graph" yielding a 403 error
  src/views/portfolio/projects/Project.vue
  src/views/portfolio/projects/ProjectDependencyGraph.vue
Labels: defect

#1218 Display last vuln analysis timestamp in project view
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/portfolio/projects/ProjectDashboard.vue
Labels: enhancement

#1220 Bump nginx base image to latest digest
  docker/Dockerfile.alpine
Labels: dependencies

#1227 Improve German Translation
  src/i18n/locales/de.json
  src/views/portfolio/projects/ProjectPolicyViolations.vue
Labels: enhancement, i18n

#1237 Show collection projects using tag in tag list
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/portfolio/tags/TagList.vue
  src/views/portfolio/tags/TaggedCollectionProjectListModal.vue
Labels: enhancement, backport/4.13.1

#1242 build(deps): bump nginxinc/nginx-unprivileged from 1.27.4-alpine to 1.27.5-alpine in /docker
  docker/Dockerfile.alpine
Labels: dependencies

#1241 Show collection projects using tag in tag list
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/portfolio/tags/TagList.vue
  src/views/portfolio/tags/TaggedCollectionProjectListModal.vue
Labels: enhancement
